### ISSUE TITLE
snmptrap - NameError: global name 'Alert' is not defined

### ISSUE THREAD

**Issue by gugansankar** [alerta/alerta-contrib#176]
I don't receive any trap message in Alerta , So I run the snmptrapd in debug mode where I see , this exception message from alertasnmp

Logs:

2017-12-20 07:01:50,902 - alerta.snmptrap: DEBUG - $1 1:18:47:46.42
2017-12-20 07:01:50,902 - alerta.snmptrap: DEBUG - $2 IF-MIB::linkDown.0
2017-12-20 07:01:50,902 - alerta.snmptrap: DEBUG - $3 "This is a test linkDown trap"
2017-12-20 07:01:50,902 - alerta.snmptrap: DEBUG - varbinds = {u'DISMAN-EVENT-MIB::sysUpTimeInstance': u'1:18:47:46.42', u'SNMPv2-SMI::zeroDotZero': u'"This is a test linkDown trap"', u'SNMPv2-MIB::snmpTrapOID.0': u'IF-MIB::linkDown.0'}
2017-12-20 07:01:50,902 - alerta.snmptrap: DEBUG - trapvars = {u'$N': u'.', '$O': u'IF-MIB::linkDown.0', '$1': u'1:18:47:46.42', u'$X': u'01:31:50', '$3': u'"This is a test linkDown trap"', u'$b': u'UDP: [10.11.12.169]:49858->[10.11.12.147]:162', u'$T': u'0', u'$B': u'<UNKNOWN>', '$#': '3', u'$A': u'0.0.0.0', u'$x': u'2017-12-20', u'$W': 'Link Down', u'$w': '2', u'$t': u'1513733510', u'$a': u'0.0.0.0', '$2': u'IF-MIB::linkDown.0', u'$s': 'SNMPv2c', u'$P': u'TRAP2, SNMP v2c, community public', u'$q': u'0'}
2017-12-20 07:01:50,903 - alerta.snmptrap: INFO - SNMPv2c-Trap-PDU IF-MIB::linkDown.0 from <UNKNOWN> at 2017-12-20 01:31:50
2017-12-20 07:01:50,903 - alerta.snmptrap: ERROR - global name 'Alert' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/handler.py", line 190, in main
    SnmpTrapHandler().run()
  File "/usr/lib/python2.7/site-packages/handler.py", line 37, in run
    snmptrapAlert = SnmpTrapHandler.parse_snmptrap(data)
  File "/usr/lib/python2.7/site-packages/handler.py", line 163, in parse_snmptrap
    snmptrapAlert = Alert(
NameError: global name 'Alert' is not defined

**Comment by satterly** [comment]
Looks like the snmp trap handler hasn't been updated to work with the latest version of the Alerta python SDK.

**Comment by satterly** [comment]
Should be fixed in version 5.0. Please test.
