### ISSUE TITLE
azuremonitor new format creates service as string literal, but it should be array

### ISSUE THREAD

**Issue by oyvindhorneland** [alerta/alerta-contrib#236]
**Describe the bug**

malformed array literal with webhook from Azure:

```
2019-02-06 14:17:11,030 DEBG 'uwsgi' stdout output:
ERROR:flask.app:Error while running pre-receive plugin 'alerta.plugins.blackout': malformed array literal: "Microsoft.Compute/virtualMachines"
LINE 15: ...             OR ( resource IS NULL AND service <@ 'Microsoft...
                                                              ^
DETAIL:  Array value must start with "{" or dimension information.
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/alerta/utils/api.py", line 46, in process_alert
    alert = plugin.pre_receive(alert)
  File "/venv/lib/python3.6/site-packages/alerta/plugins/blackout.py", line 21, in pre_receive
    if alert.is_blackout():
  File "/venv/lib/python3.6/site-packages/alerta/models/alert.py", line 374, in is_blackout
    return db.is_blackout_period(self)
  File "/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py", line 650, in is_blackout_period
    if self._fetchone(select, vars(alert)):
  File "/venv/lib/python3.6/site-packages/alerta/database/backends/postgres/base.py", line 1115, in _fetchone
    cursor.execute(query, vars)
  File "/venv/lib/python3.6/site-packages/psycopg2/extras.py", line 313, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
psycopg2.DataError: malformed array literal: "Microsoft.Compute/virtualMachines"
LINE 15: ...             OR ( resource IS NULL AND service <@ 'Microsoft...
                                                              ^
DETAIL:  Array value must start with "{" or dimension information.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/alerta/webhooks/custom.py", line 35, in custom
    alert = process_alert(response)
  File "/venv/lib/python3.6/site-packages/alerta/utils/api.py", line 51, in process_alert
    raise RuntimeError("Error while running pre-receive plugin '{}': {}".format(plugin.name, str(e)))
RuntimeError: Error while running pre-receive plugin 'alerta.plugins.blackout': malformed array literal: "Microsoft.Compute/virtualMachines"
LINE 15: ...             OR ( resource IS NULL AND service <@ 'Microsoft...
                                                              ^
DETAIL:  Array value must start with "{" or dimension information.
```
Webhook payload
```
{
    "schemaId": "AzureMonitorMetricAlert",
    "data": {
        "version": "2.0",
        "properties": null,
        "status": "Activated",
        "context": {
            "timestamp": "2019-02-05T21:19:47.4688345Z",
            "id": "/subscriptions/<EDITED>/resourceGroups/<EDITED>/providers/microsoft.insights/metricAlerts/<EDITED>",
            "name": "Test percentage cpu",
            "description": "Blablabla description here",
            "conditionType": "SingleResourceMultipleMetricCriteria",
            "severity": "3",
            "condition": {
                "windowSize": "PT1M",
                "allOf": [
                    {
                        "metricName": "Percentage CPU",
                        "metricNamespace": "Microsoft.Compute/virtualMachines",
                        "operator": "GreaterThan",
                        "threshold": "2",
                        "timeAggregation": "Average",
                        "dimensions": [
                            {
                                "name": "ResourceId",
                                "value": "<EDITED>"
                            }
                        ],
                        "metricValue": 8.1875
                    }
                ]
            },
            "subscriptionId": "<EDITED>,
            "resourceGroupName": "<EDITED>",
            "resourceName": "<EDITED>",
            "resourceType": "Microsoft.Compute/virtualMachines",
            "resourceId": "/subscriptions/<EDITED>/resourceGroups/<EDITED>/providers/Microsoft.Compute/virtualMachines/<EDITED>",
            "portalLink": "https://portal.azure.com/#resource/subscriptions/<EDITED>/resourceGroups/<EDITED>/providers/Microsoft.Compute/virtualMachines/<EDITED>"
        }
    }
}
```

**To Reproduce**

See webhook payload. Blackout plugin and azuremonitor webhook must be enabled.

**Expected behavior**
The webhook payload should be accepted.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Old format maps service like this:
`service         = [payload['context']['resourceType']]`

New format maps it like this:
`service         = payload['data']['context']['resourceType']`

With PostgreSQL backend and a resourceType of "Microsoft.Compute/virtualMachines" the blackout plugin fails to execute SQL since it expects an array.

**Comment by satterly** [comment]
Fixed by #236
